services:
  backend:
    image: cvtalrc/gc-ai-backend 
    ports:
      - "5001:5001"
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "igemparts2024"
      DB_NAME: "iGEM2024"
      APP_HOST: '0.0.0.0'
      APP_PORT: "5001"
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: cvtalrc/gc-ai-frontend  
    ports:
      - "8081:80"
    environment:
      VITE_API_BASE_URL: "http://localhost:5001"
    networks:
      - app_network
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: cvtalrc/gc-ai-db  
    container_name: igem_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "igemparts2024"
      MYSQL_DATABASE: "iGEM2024"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
     
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 240s

volumes:
  db-data:  

networks:
  app_network:
    driver: bridge
  
